language: java
jdk:
- oraclejdk8
before_install:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
install: true
script:
- ./mvnw clean deploy $( [[ $TRAVIS_COMMIT_MESSAGE =~ .*doRelease.* ]] && echo "-Prelease" )
